# Generated by Django 5.2.7 on 2026-10-07 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_ssologinticket_ssoidentity'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSOLoginFlow',
            fields=[
                ('state_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('nonce', models.CharField(max_length=128)),
                ('code_verifier', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
